// PREMADE ROSTERS: a whole cast, one click, at world creation.
//
// Designing twelve characters by hand before you've played a single night is
// the longest wall in setup, and the reason a lot of runs never start. These
// are eight complete casts from the games the genre is actually made of — the
// tournament classic, the party platform fighter, the 3D clan drama, the anime
// power ladder, the gore-tournament, the crossover, the rock opera, the
// superhero fighter — with the real fighters and the real movelists, so a run
// can open with a roster you already know how to read.
//
// FAN CONTENT. Every name in this file belongs to somebody else — Capcom,
// Nintendo, Bandai Namco, Toei, NetherRealm, Marvel, Arc System Works, DC.
// This is a personal, non-commercial build; if this ever went out to more than
// a handful of people, the fix is one pass over the data below and nothing
// else in the codebase, which is exactly why the casts live in a single file.
//
// The archetype kit does the heavy lifting. Each spec names an archetype, and
// `applyArchetypeKit` builds the full movelist, the body and the starter combos
// from it — this file only renames the specials and the super, and pins the
// dials the kit would otherwise roll. So a preset cast is balanced by exactly
// the same rules a hand-built one is, and nothing here can invent a stat line
// the editor couldn't produce. That does mean a move occasionally lands in a
// slot its original wasn't (a "counter" named Spinning Bird Kick): the kit's
// SHAPE is the archetype's, and the names are dressed onto it in order.

import { newCharacter, newMove } from './model.js'
import { applyArchetypeKit, applyMoveDescriptors } from './design.js'
import { newSkin } from './skins.js'
import { FORM_MOVE_TYPE } from './constants.js'

// ---------- Building ----------

/** Rename the kit's specials in order, then the super. Extras are ignored. */
function renameMoves(char, spec) {
  const specials = (char.moves || []).filter((m) => m.slot === 'special')
  for (const [i, name] of (spec.specials || []).entries()) {
    if (specials[i]) specials[i].name = name
  }
  const sup = (char.moves || []).find((m) => m.slot === 'super')
  if (sup && spec.super) sup.name = spec.super
}

function buildOne(spec, gameTags) {
  const char = newCharacter({ name: spec.name })
  applyArchetypeKit(char, spec.archetype, gameTags)
  renameMoves(char, spec)
  // The kit rolls these; a preset means them. A cast where the difficulty and
  // the draw are authored is the difference between twelve characters and a
  // roster with a shape to it.
  if (spec.description) char.description = spec.description
  if (spec.difficulty != null) char.difficulty = spec.difficulty
  if (spec.popularity != null) char.popularity = spec.popularity
  if (spec.vitality) char.vitality = spec.vitality
  if (spec.size) char.size = spec.size
  // A pack sprite key, namespaced `pack/name` — see components/art.js. A key
  // naming art that isn't on disk resolves to null there and falls back to the
  // archetype stand-in, so a preset never ships a broken image.
  if (spec.spriteKey) char.spriteKey = spec.spriteKey
  for (const s of spec.skins || []) char.skins.push(newSkin(s))
  char.tags = [...new Set([...(char.tags || []), ...(spec.tags || [])])]
  return char
}

/** A spec's forms, however it spelled them: one `form`, or a list. */
const formsIn = (spec) => spec.forms || (spec.form ? [spec.form] : [])

/** A form-change move pointing at `targetId`, authored rather than rolled. */
function switchMove(name, targetId, { cost = 'full bar', startup = 'average', recovery = 'slow', onBlock = 'punishable' } = {}) {
  const m = newMove({ type: FORM_MOVE_TYPE, name })
  m.d = { ...m.d, form: 'transformation', cost, startup, recovery, onBlock, becomes: targetId }
  return applyMoveDescriptors(m)
}

/**
 * Mint a preset's cast: fresh ids every call, so loading the same roster twice
 * gives two independent casts rather than a save full of collided ids.
 *
 * Call this OUTSIDE an `update()` — the setup wizard runs updates inside a
 * React state updater, where ids minted in there aren't reliably readable
 * afterwards, and the form links here are ids pointing at ids.
 */
export function buildPresetRoster(key) {
  const preset = PRESET_ROSTERS.find((p) => p.key === key)
  if (!preset) return null
  const characters = []
  for (const spec of preset.characters) {
    const char = buildOne(spec, preset.tags)
    characters.push(char)
    // A form is a complete character nobody can pick — see forms.js. The origin
    // buys its way in with meter; each form gets a way home, so a
    // transformation is a decision rather than a one-way cutscene. A character
    // may have several (a tag team, a party of three), but forms are one level
    // deep: a form never has forms of its own.
    for (const fSpec of formsIn(spec)) {
      const form = buildOne(fSpec, preset.tags)
      form.formOf = char.id
      char.moves.push(switchMove(fSpec.via || 'Transform', form.id))
      form.moves.push(switchMove(fSpec.revert || 'Power Down', char.id,
        { cost: 'none', startup: 'fast', recovery: 'average', onBlock: 'minus' }))
      characters.push(form)
    }
  }
  return { preset, characters }
}

export const presetRoster = (key) => PRESET_ROSTERS.find((p) => p.key === key) || null

/** How many pickable fighters a preset ships (forms don't count — see forms.js). */
export const presetSize = (preset) => preset?.characters?.length || 0

// ---------- The casts ----------

export const PRESET_ROSTERS = [
  {
    key: 'street-fighter',
    name: 'Street Fighter',
    gameName: 'Street Fighter',
    blurb: 'The World Warriors and the four Grand Masters — the twelve that set the rules everybody else is still following.',
    tags: ['honest', 'classic', 'military', 'monster', 'flashy', 'royal'],
    characters: [
      { name: 'Ryu', archetype: 'Shoto', difficulty: 3, popularity: 9,
        tags: ['honest', 'classic'],
        description: 'The wandering ascetic. The character every new player is handed and every veteran still respects.',
        specials: ['Hadoken', 'Shoryuken', 'Tatsumaki Senpukyaku', 'Collarbone Breaker'],
        super: 'Shinku Hadoken' },
      { name: 'Ken Masters', archetype: 'Shoto', difficulty: 4, popularity: 8,
        tags: ['flashy', 'classic'],
        description: 'Same school, half the discipline, twice the showmanship. Trades the fireball game for a flaming uppercut.',
        specials: ['Hadoken', 'Shoryuken', 'Tatsumaki Senpukyaku', 'Inazuma Kick'],
        super: 'Shoryureppa' },
      { name: 'Chun-Li', archetype: 'Charge', difficulty: 5, popularity: 9,
        tags: ['honest', 'cool'],
        description: 'The strongest woman in the world. Wins the fight an inch at a time, with legs.',
        specials: ['Kikoken', 'Tenshokyaku', 'Hazanshu', 'Spinning Bird Kick'],
        super: 'Kikosho' },
      { name: 'Guile', archetype: 'Zoner', difficulty: 5, popularity: 8,
        tags: ['military', 'cheap'],
        description: 'Charges back, waits, and makes you come to him. Half the screen is his and he charges rent.',
        specials: ['Sonic Boom', 'Sonic Break', 'Sonic Blade', 'Flash Kick'],
        super: 'Sonic Hurricane' },
      { name: 'Zangief', archetype: 'Grappler', difficulty: 5, popularity: 7,
        tags: ['big damage', 'monster'],
        description: 'The Red Cyclone. Walks forward all round and only has to be right once.',
        specials: ['Screw Piledriver', 'Double Lariat', 'Banishing Flat', 'Green Hand'],
        super: 'Final Atomic Buster' },
      { name: 'Dhalsim', archetype: 'Zoner', difficulty: 7, popularity: 5,
        tags: ['technical', 'cheap'],
        description: 'Limbs that go further than limbs go, and a yoga master who would rather not be here.',
        specials: ['Yoga Fire', 'Yoga Arch', 'Yoga Flame', 'Yoga Blast'],
        super: 'Yoga Inferno' },
      { name: 'Blanka', archetype: 'Rushdown', difficulty: 5, popularity: 7,
        tags: ['monster', 'goofy'],
        description: 'Raised by the jungle, electrified by something nobody has explained. Bites, rolls, never blocks.',
        specials: ['Rolling Attack', 'Amazon River Run', 'Electric Thunder', 'Vertical Roll'],
        super: 'Ground Shave Rolling' },
      { name: 'E. Honda', archetype: 'Big Body', difficulty: 4, popularity: 6,
        tags: ['monster', 'big damage'],
        description: 'A yokozuna who fills the screen standing still. Every button he presses is a wall arriving.',
        specials: ['Sumo Smash', 'Oicho Throw', 'Sumo Headbutt', 'Hundred Hand Slap'],
        super: 'Ultimate Killer Head Ram' },
      { name: 'Balrog', archetype: 'Rushdown', difficulty: 3, popularity: 7,
        tags: ['big damage', 'edgy'],
        description: 'A boxer who was banned for killing a man in the ring. Dashes forward and does not stop.',
        specials: ['Dash Low Smash', 'Dash Straight', 'Turn Punch', 'Dash Upper'],
        super: 'Crazy Buffalo' },
      { name: 'Vega', archetype: 'Aerial', difficulty: 6, popularity: 8,
        tags: ['royal', 'creepy'],
        description: 'A Spanish noble with a claw and a mask, who fights off the cage wall and hates ugly things.',
        specials: ['Flying Barcelona Attack', 'Sky High Claw', 'Izuna Drop', 'Scarlet Terror'],
        super: 'Bloody High Claw' },
      { name: 'Sagat', archetype: 'Zoner', difficulty: 4, popularity: 8,
        tags: ['big damage', 'classic'],
        description: 'The one-eyed Emperor of Muay Thai, carrying a scar and a rematch he has waited years for.',
        specials: ['Tiger Shot', 'Low Tiger Shot', 'Tiger Cannon', 'Tiger Uppercut'],
        super: 'Tiger Genocide' },
      { name: 'M. Bison', archetype: 'Mix-up', difficulty: 6, popularity: 8,
        tags: ['edgy', 'royal'],
        description: 'Shadaloo\'s dictator, running on Psycho Power. Teleports behind you and the guessing game starts there.',
        specials: ['Bison Warp', 'Head Press', 'Psycho Inferno', 'Devil Reverse'],
        super: 'Psycho Crusher' },
    ],
  },

  {
    key: 'smash-bros',
    name: 'Super Smash Bros.',
    gameName: 'Super Smash Bros.',
    blurb: 'The original twelve off the N64 disc — mascots, animals and swordsmen from a dozen worlds, none of them balanced against each other.',
    tags: ['cute', 'goofy', 'classic', 'flashy', 'monster', 'underdog'],
    characters: [
      { name: 'Mario', archetype: 'All-Rounder', difficulty: 2, popularity: 10,
        tags: ['classic', 'cute'],
        description: 'The mascot. A tool for every situation, a weakness nowhere, and the face on the box.',
        specials: ['Fireball', 'Super Jump Punch', 'Cape', 'Mario Tornado'],
        super: 'Mario Finale' },
      { name: 'Donkey Kong', archetype: 'Big Body', difficulty: 3, popularity: 8,
        tags: ['monster', 'big damage'],
        description: 'Barrel chest, necktie, and a wind-up punch you can see coming from the parking lot.',
        specials: ['Giant Punch', 'Cargo Throw', 'Spinning Kong', 'Hand Slap'],
        super: 'Konga Beat' },
      { name: 'Link', archetype: 'Weapon Master', difficulty: 5, popularity: 9,
        tags: ['honest', 'cool'],
        description: 'Sword, shield and a bag of tools. Fights at exactly the range where his steel is and your fists are not.',
        specials: ['Spin Attack', 'Jump Slash', 'Down Thrust', 'Up Thrust', 'Boomerang'],
        super: 'Triforce Slash' },
      { name: 'Samus', archetype: 'Zoner', difficulty: 5, popularity: 7,
        tags: ['military', 'technical'],
        description: 'A bounty hunter in a suit of borrowed Chozo engineering. Charges a beam and makes the screen a hallway.',
        specials: ['Charge Shot', 'Missile', 'Bomb', 'Screw Attack'],
        super: 'Zero Laser' },
      { name: 'Yoshi', archetype: 'Grappler', difficulty: 4, popularity: 8,
        tags: ['cute', 'goofy'],
        description: 'Eats you, and what comes out the other side is an egg. Genuinely one of the best air games on the roster.',
        specials: ['Egg Lay', 'Yoshi Bomb', 'Egg Throw', 'Egg Roll'],
        super: 'Super Dragon' },
      { name: 'Kirby', archetype: 'Stance Switch', difficulty: 8, popularity: 9,
        tags: ['cute', 'technical'],
        description: 'A pink sphere that swallows what you do and does it back. Two characters in one, neither threatening to look at.',
        specials: ['Copy', 'Stone', 'Hammer Flip', 'Inhale'],
        super: 'Cook Kirby' },
      { name: 'Fox', archetype: 'Rushdown', difficulty: 6, popularity: 8,
        tags: ['cool', 'flashy'],
        description: 'A pilot fighting on foot because the ship is in the shop. Never stops moving; never stops talking either.',
        specials: ['Fox Illusion', 'Fire Fox', 'Blaster', 'Reflector'],
        super: 'Landmaster' },
      { name: 'Pikachu', archetype: 'Aerial', difficulty: 4, popularity: 10,
        tags: ['cute', 'flashy'],
        description: 'Small, yellow, everywhere at once. The plush toy that beats you at a national.',
        specials: ['Quick Attack', 'Thunder', 'Skull Bash', 'Thunder Jolt'],
        super: 'Volt Tackle' },
      { name: 'Luigi', archetype: 'Glass Cannon', difficulty: 6, popularity: 8,
        tags: ['goofy', 'underdog'],
        description: 'The taller brother. Slippier, sadder, and carrying one button that occasionally deletes a stock by accident.',
        specials: ['Negative Zone', 'Green Missile', 'Luigi Cyclone', 'Super Jump Punch'],
        super: 'Poltergust G-00' },
      { name: 'Captain Falcon', archetype: 'Counter-Puncher', difficulty: 6, popularity: 9,
        tags: ['cool', 'flashy'],
        description: 'A bounty hunter who races between jobs. Waits, reads, and lands one fist the whole room stands up for.',
        specials: ['Falcon Dive', 'Raptor Boost', 'Falcon Punch', 'Falcon Kick'],
        super: 'Blue Falcon' },
      { name: 'Ness', archetype: 'Setplay', difficulty: 7, popularity: 6,
        tags: ['underdog', 'technical'],
        description: 'A kid in a baseball cap with psychic powers and a yo-yo. One knockdown and the floor stops being yours.',
        specials: ['PK Fire', 'PK Flash', 'PSI Magnet', 'Yo-Yo'],
        super: 'PK Starstorm' },
      { name: 'Jigglypuff', archetype: 'Mix-up', difficulty: 7, popularity: 6,
        tags: ['cute', 'goofy'],
        description: 'Six jumps, no ground game, and one button that ends the stock if you ever fall asleep on defence.',
        specials: ['Rollout', 'Pound', 'Sing', 'Rest'],
        super: 'Puff Up' },
    ],
  },

  {
    key: 'tekken',
    name: 'Tekken',
    gameName: 'Tekken',
    blurb: 'The King of Iron Fist Tournament: a corporate family throwing each other off cliffs, and a movelist per character longer than most games have in total.',
    tags: ['technical', 'edgy', 'classic', 'cool', 'monster', 'royal'],
    characters: [
      { name: 'Kazuya Mishima', archetype: 'Counter-Puncher', difficulty: 9, popularity: 9,
        tags: ['edgy', 'technical'],
        description: 'Thrown off a cliff as a child by his own father, and came back with something else living behind his eyes.',
        specials: ['Demon Slayer', 'Devil Twister', 'Electric Wind God Fist', 'Wavedash'],
        super: 'Rage Art',
        form: { name: 'Devil Kazuya', archetype: 'Glass Cannon', difficulty: 9, popularity: 9,
          tags: ['edgy', 'monster'],
          description: 'The thing that survived the cliff. Wings, a forehead laser, and none of the restraint.',
          specials: ['Devil Aura', "Devil's Fist", 'Devil Wing Dash', 'Devil Twister'],
          super: 'Devil Blaster',
          via: 'Devil Transformation', revert: 'Suppress the Devil' } },
      { name: 'Jin Kazama', archetype: 'Stance Switch', difficulty: 8, popularity: 10,
        tags: ['technical', 'cool'],
        description: 'The son who threw the family style away and rebuilt it clean, holding a bloodline at arm\'s length.',
        specials: ['Zenshin', 'Mental Alertness', 'Median Line Destruction', 'Kazama-Style Parry'],
        super: 'Rage Art' },
      { name: 'Paul Phoenix', archetype: 'Glass Cannon', difficulty: 5, popularity: 8,
        tags: ['big damage', 'goofy'],
        description: 'Judo, a haircut with its own gravity, and one punch that ends the round if it ever lands.',
        specials: ['Phoenix Stance', 'Deathfist', 'Sway Step', 'Falling Leaf'],
        super: 'Burning Fist' },
      { name: 'King', archetype: 'Grappler', difficulty: 8, popularity: 9,
        tags: ['big damage', 'cool'],
        description: 'A masked luchador funding an orphanage on prize money. Once he has your wrist, the round is a cutscene.',
        specials: ['Giant Swing', 'Konvict Kick', 'Jaguar Sprint', 'Jaguar Step'],
        super: 'Muscle Buster' },
      { name: 'Nina Williams', archetype: 'Mix-up', difficulty: 7, popularity: 8,
        tags: ['cool', 'edgy'],
        description: 'A contract killer who has been thirty for forty years. Every string ends in a joint that no longer works.',
        specials: ['Sidewinder', 'Ivory Cutter', 'Blonde Bomb', 'Skull Splitter'],
        super: 'Geyser Cannon' },
      { name: 'Yoshimitsu', archetype: 'Weapon Master', difficulty: 9, popularity: 7,
        tags: ['creepy', 'technical'],
        description: 'A masked thief in mechanical armour with a sword and no interest in explaining any of it.',
        specials: ['Manji Blood Dance', 'Flash', 'Poison Wind', 'Kangaroo Kick', 'Sword Poke'],
        super: 'Rainbow Drop' },
      { name: 'Marshall Law', archetype: 'Rushdown', difficulty: 6, popularity: 8,
        tags: ['flashy', 'classic'],
        description: 'Runs a restaurant that keeps burning down. Fights in strings so fast the block button becomes a prayer.',
        specials: ['Fake Step', 'Rave War Combo', 'Dragon Knuckle', 'Somersault Kick'],
        super: "Dragon's Tail" },
      { name: 'Hwoarang', archetype: 'Footsies', difficulty: 8, popularity: 8,
        tags: ['cool', 'honest'],
        description: 'Taekwondo, a bad attitude, and a stance that turns every step into four different kicks.',
        specials: ['Backlash', 'Flamingo Step', 'Hunting Hawk', 'Fire Cracker'],
        super: 'Sky Rocket' },
      { name: 'Jack-8', archetype: 'Charge', difficulty: 4, popularity: 6,
        tags: ['monster', 'military'],
        description: 'Two and a half metres of surplus military hardware that keeps entering the tournament on a technicality.',
        specials: ['Photon Cannon', 'Sonic Fist', 'Megaton Punch', 'Power Guard'],
        super: 'Gigaton Punch' },
      { name: 'Ling Xiaoyu', archetype: 'Aerial', difficulty: 8, popularity: 9,
        tags: ['cute', 'technical'],
        description: 'A schoolgirl who entered to win an amusement park. Spins, hops, and is never standing where you swung.',
        specials: ['Wind Roll', 'Storming Flower', 'Rain Dance', 'Skyscraper Kick'],
        super: 'Hypnotist' },
      { name: 'Bryan Fury', archetype: 'Big Body', difficulty: 7, popularity: 8,
        tags: ['edgy', 'monster'],
        description: 'A dead cop wired to a power core that will not stop. Laughs at you, then punishes the button you pressed about it.',
        specials: ['Mach Breaker', 'Northern Lights Suplex', 'Jet Upper', 'Taunt'],
        super: 'Snake Pit' },
      { name: 'Alisa Bosconovitch', archetype: 'Setplay', difficulty: 8, popularity: 7,
        tags: ['cute', 'technical'],
        description: 'An android built by a grieving father, with chainsaw forearms and a detachable head that explodes.',
        specials: ['Head Bomb', 'Spam Bot', 'Destructive Form', 'Dual Boot'],
        super: 'Terminate' },
    ],
  },

  {
    key: 'dragon-ball-z',
    name: 'Dragon Ball Z',
    gameName: 'Dragon Ball Z',
    blurb: 'The power ladder: beams that fill the screen, transformations that rewrite the tier list mid-round, and everybody screaming.',
    tags: ['anime', 'flashy', 'big damage', 'monster', 'cool', 'royal'],
    characters: [
      { name: 'Goku', archetype: 'Shoto', difficulty: 4, popularity: 10,
        tags: ['anime', 'honest'],
        description: 'A Saiyan raised on Earth who fights because it is the only thing that has ever felt like talking.',
        specials: ['Kamehameha', 'Dragon Fist', 'Meteor Combination', 'Instant Transmission'],
        super: 'Spirit Bomb',
        form: { name: 'Super Saiyan Goku', archetype: 'Glass Cannon', difficulty: 5, popularity: 10,
          tags: ['anime', 'big damage'],
          description: 'Gold hair, no patience, and a damage output the balance team has never once been happy with.',
          specials: ['Super Saiyan Aura', 'Meteor Smash', 'Instant Transmission', 'Dragon Fist'],
          super: 'Super Kamehameha',
          via: 'Super Saiyan', revert: 'Power Down' } },
      { name: 'Vegeta', archetype: 'Charge', difficulty: 6, popularity: 9,
        tags: ['royal', 'edgy'],
        description: 'The last prince of a dead world, permanently one place below where he believes he should be.',
        specials: ['Galick Gun', 'Big Bang Attack', 'Meteor Crash', 'Ki Guard'],
        super: 'Final Flash',
        form: { name: 'Super Vegeta', archetype: 'Glass Cannon', difficulty: 7, popularity: 9,
          tags: ['royal', 'big damage'],
          description: 'Pride converted directly into damage. Nothing about the defence improved.',
          specials: ['Super Saiyan Aura', 'Atomic Blast', 'Afterimage', 'Big Bang Attack'],
          super: 'Final Flash',
          via: 'Super Saiyan', revert: 'Power Down' } },
      { name: 'Piccolo', archetype: 'Zoner', difficulty: 6, popularity: 8,
        tags: ['anime', 'cool'],
        description: 'A demon king turned reluctant mentor. Fights from range because everything he cares about stands behind him.',
        specials: ['Special Beam Cannon', 'Masenko', 'Hellzone Grenade', 'Chasing Bullet'],
        super: 'Light Grenade' },
      { name: 'Gohan', archetype: 'Glass Cannon', difficulty: 7, popularity: 8,
        tags: ['anime', 'underdog'],
        description: 'A quiet student with more power in him than anyone on the roster and no wish to use it.',
        specials: ['Potential Unleashed', 'Soaring Fist', 'Afterimage', 'Machine Gun Punch'],
        super: 'Father-Son Kamehameha' },
      { name: 'Frieza', archetype: 'Mix-up', difficulty: 8, popularity: 9,
        tags: ['edgy', 'royal'],
        description: 'Polite, small, and the reason several planets are not on the map. Never raises his voice until the next form.',
        specials: ['Blink', 'Tail Grab', 'Death Saucer', 'Death Chop'],
        super: 'Supernova',
        form: { name: 'Final Form Frieza', archetype: 'Glass Cannon', difficulty: 8, popularity: 9,
          tags: ['edgy', 'monster'],
          description: 'The shape under the polite one, at a hundred percent. Nothing about it is small.',
          specials: ['100% Power', 'Death Slicer', 'Instant Teleport', 'Death Cannon'],
          super: 'Nova Strike',
          via: 'Transform', revert: 'Suppress Power' } },
      { name: 'Majin Buu', archetype: 'Big Body', difficulty: 4, popularity: 8,
        tags: ['monster', 'goofy'],
        description: 'Pink, cheerful and completely without a stopping condition. Regenerates while apologising.',
        specials: ['Chocolate Kick', 'Absorption', 'Buu Rush', 'Regeneration'],
        super: 'Planet Burst' },
      { name: 'Krillin', archetype: 'Setplay', difficulty: 7, popularity: 7,
        tags: ['underdog', 'technical'],
        description: 'The strongest ordinary human alive, which on this roster means he has to be clever about it.',
        specials: ['Destructo Disc', 'Scattering Bullet', 'Solar Flare', 'Sweep Kick'],
        super: 'Scattering Energy Wave' },
      { name: 'Trunks', archetype: 'Weapon Master', difficulty: 6, popularity: 9,
        tags: ['cool', 'anime'],
        description: 'Arrived from a future where everyone on this roster is already dead. Fights with a sword and no small talk.',
        specials: ['Burning Slash', 'Shining Sword Attack', 'Sword Sweep', 'Rising Slash', 'Hilt Strike'],
        super: 'Heat Dome Attack' },
      { name: 'Tien Shinhan', archetype: 'All-Rounder', difficulty: 6, popularity: 6,
        tags: ['technical', 'honest'],
        description: 'A former assassin who now fights on principle, and pays for his best attack with his own health.',
        specials: ['Dodon Ray', 'Volleyball Fist', 'Four Witches Technique', 'Multi-Form'],
        super: 'Tri-Beam' },
      { name: 'Android 18', archetype: 'Footsies', difficulty: 6, popularity: 8,
        tags: ['cool', 'cheap'],
        description: 'A converted human with an infinite battery and a bored expression. Never runs out of anything.',
        specials: ['Barrier', 'Afterimage', 'Deadly Dance', 'Sweep Kick'],
        super: 'Accel Dance' },
      { name: 'Broly', archetype: 'Grappler', difficulty: 5, popularity: 9,
        tags: ['monster', 'big damage'],
        description: 'A legend that turned out to be a person. Grabs planets; will settle for you.',
        specials: ['Gigantic Press', 'Blaster Shell', 'Eraser Cannon', 'Burst Rush'],
        super: 'Gigantic Meteor' },
      { name: 'Cell', archetype: 'Counter-Puncher', difficulty: 8, popularity: 8,
        tags: ['creepy', 'technical'],
        description: 'A bio-android assembled from everyone else\'s cells, which is why he already knows what you are about to do.',
        specials: ['Absorb', 'Barrier', 'Perfect Attack', 'Instant Transmission'],
        super: 'Solar Kamehameha' },
    ],
  },

  {
    key: 'mortal-kombat',
    name: 'Mortal Kombat',
    gameName: 'Mortal Kombat',
    blurb: 'The tournament for Earthrealm: two ninjas with a blood feud, a thunder god, four-armed royalty, and a finisher for every one of them.',
    tags: ['edgy', 'creepy', 'monster', 'big damage', 'military', 'royal'],
    characters: [
      { name: 'Scorpion', archetype: 'Zoner', difficulty: 5, popularity: 10,
        tags: ['edgy', 'creepy'],
        description: 'Burned to death, came back angry, and has been dragging people toward him with a chain ever since.',
        specials: ['Spear', 'Hellfire', 'Hell Portal', 'Teleport Punch'],
        super: "Hell's Fury" },
      { name: 'Sub-Zero', archetype: 'Setplay', difficulty: 6, popularity: 10,
        tags: ['cool', 'technical'],
        description: 'The other half of the feud. Freezes the floor, leaves a copy of himself standing on it, and waits.',
        specials: ['Ice Puddle', 'Ice Clone', 'Ice Armor', 'Slide'],
        super: 'Deep Freeze' },
      { name: 'Raiden', archetype: 'Charge', difficulty: 5, popularity: 8,
        tags: ['royal', 'flashy'],
        description: 'A god who keeps having to explain the rules to mortals, then flies through them head first.',
        specials: ['Lightning', 'Shocker', 'Torpedo', 'Static Trap'],
        super: 'Electrocute' },
      { name: 'Liu Kang', archetype: 'Shoto', difficulty: 3, popularity: 9,
        tags: ['honest', 'classic'],
        description: 'A Shaolin monk carrying the tournament on his back. Fireball, dragon kick, and a bicycle kick nobody blocks twice.',
        specials: ['Fireball', "Dragon's Roar", 'Flying Dragon Kick', 'Dragon Dash'],
        super: 'Bicycle Kick' },
      { name: 'Sonya Blade', archetype: 'Rushdown', difficulty: 5, popularity: 8,
        tags: ['military', 'cool'],
        description: 'Special Forces, here for one specific criminal, happy to go through eleven people to get to him.',
        specials: ['Air Drop', 'Arc Kick', 'Energy Rings', 'Leg Grab'],
        super: 'Kiss of Death' },
      { name: 'Johnny Cage', archetype: 'Counter-Puncher', difficulty: 6, popularity: 9,
        tags: ['goofy', 'flashy'],
        description: 'An actor whose career needed this. Turns out the shades were not the only thing he brought.',
        specials: ['Mime Time', 'Green Fireball', 'Split Punch', 'Shadow Kick'],
        super: 'Rising Shadow' },
      { name: 'Kano', archetype: 'Mix-up', difficulty: 6, popularity: 7,
        tags: ['edgy', 'cheap'],
        description: 'A knife, a metal eye, and no side but his own. Cannonballs across the screen and grins about it.',
        specials: ['Cannonball', 'Choke', 'Knife Toss', 'Up Ball'],
        super: 'Eye Laser' },
      { name: 'Goro', archetype: 'Big Body', difficulty: 4, popularity: 8,
        tags: ['monster', 'royal'],
        description: 'Shokan royalty with twice the arms, undefeated for five hundred years and not interested in a fair fight.',
        specials: ['Punch Walk', 'Shokan Grab', 'Leaping Stomp', 'Shokan Guard'],
        super: 'Shokan Rage' },
      { name: 'Shang Tsung', archetype: 'Stance Switch', difficulty: 9, popularity: 7,
        tags: ['creepy', 'technical'],
        description: 'A sorcerer wearing whichever face pays best today. Steals what you are and gives it back wrong.',
        specials: ['Morph', 'Soul Steal', 'Skull Barrage', 'Soul Trap'],
        super: 'Soul Devour' },
      { name: 'Reptile', archetype: 'Glass Cannon', difficulty: 7, popularity: 7,
        tags: ['creepy', 'monster'],
        description: 'The last Saurian, working for whoever will keep his species\' memory alive. Never gets to be the hero.',
        specials: ['Invisibility', 'Elbow Dash', 'Slide', 'Acid Hands'],
        super: 'Corrosive Bite' },
      { name: 'Kitana', archetype: 'Weapon Master', difficulty: 6, popularity: 9,
        tags: ['royal', 'cool'],
        description: 'Ten thousand years old, heir to a throne she has decided to burn down. Fights with steel fans.',
        specials: ['Fan Swipe', 'Square Wave Punch', 'Low Fan', 'Fan Lift', 'Fan Toss'],
        super: 'Edenian Fury' },
      { name: 'Jax', archetype: 'Grappler', difficulty: 5, popularity: 7,
        tags: ['military', 'big damage'],
        description: 'Two bionic arms and a grudge about how he got them. One grab is most of a health bar.',
        specials: ['Gotcha Grab', 'Ground Pound', 'Energy Wave', 'Dash Punch'],
        super: 'Backbreaker' },
    ],
  },

  {
    key: 'marvel-vs-capcom',
    name: 'Marvel vs. Capcom',
    gameName: 'Marvel vs. Capcom',
    blurb: 'The crossover: capes, claws and robots, air combos into the ceiling, and a super meter that never stops.',
    tags: ['flashy', 'anime', 'big damage', 'monster', 'cool', 'military'],
    characters: [
      { name: 'Wolverine', archetype: 'Rushdown', difficulty: 5, popularity: 10,
        tags: ['edgy', 'cool'],
        description: 'Short, hairy, unkillable and permanently mid-lunge. The character everybody picks first for a reason.',
        specials: ['Drill Claw', 'Berserker Barrage', 'Berserker Slash', 'Tornado Claw'],
        super: 'Weapon X' },
      { name: 'Iron Man', archetype: 'Zoner', difficulty: 6, popularity: 9,
        tags: ['technical', 'flashy'],
        description: 'A billionaire in a flying suit he built himself, which is also why he cannot stop talking during matches.',
        specials: ['Unibeam', 'Repulsor Blast', 'Smart Bomb', 'Repulsor Spread'],
        super: 'Proton Cannon' },
      { name: 'Captain America', archetype: 'Weapon Master', difficulty: 4, popularity: 8,
        tags: ['military', 'honest'],
        description: 'A soldier out of his decade with a shield that comes back. The most honest button in the game is his.',
        specials: ['Shield Slash', 'Charging Star', 'Shield Sweep', 'Stars and Stripes', 'Shield Check'],
        super: 'Final Justice' },
      { name: 'Hulk', archetype: 'Big Body', difficulty: 3, popularity: 9,
        tags: ['monster', 'big damage'],
        description: 'A scientist who is very rarely a scientist anymore. Armours through your combo and asks a question with his fist.',
        specials: ['Gamma Charge', 'Gamma Toss', 'Gamma Tornado', 'Armor Skin'],
        super: 'Gamma Crush' },
      { name: 'Storm', archetype: 'Aerial', difficulty: 7, popularity: 8,
        tags: ['cool', 'royal'],
        description: 'Weather goddess, worshipped in one country and on a team in another. Fights entirely above the health bars.',
        specials: ['Flight', 'Typhoon', 'Wind Grab', 'Lightning Attack'],
        super: 'Lightning Storm' },
      { name: 'Spider-Man', archetype: 'Mix-up', difficulty: 6, popularity: 10,
        tags: ['flashy', 'underdog'],
        description: 'A broke kid in a mask who is faster than everyone here and never shuts up about it.',
        specials: ['Web Swing', 'Web Throw', 'Web Ball', 'Spider Sting'],
        super: 'Maximum Spider' },
      { name: 'Magneto', archetype: 'Setplay', difficulty: 9, popularity: 9,
        tags: ['royal', 'technical'],
        description: 'A survivor with absolute authority over metal and no patience left for anybody\'s opinion about it.',
        specials: ['Hyper Grav', 'Magnetic Field', 'Force Field', 'Magnetic Sweep'],
        super: 'Magnetic Tempest' },
      { name: 'Doctor Doom', archetype: 'Puppet', difficulty: 9, popularity: 8,
        tags: ['royal', 'edgy'],
        description: 'A head of state in iron and a cloak. Half his kit is standing somewhere else on the screen already.',
        specials: ['Hidden Missiles', 'Molecular Shield', 'Flight', 'Plasma Beam'],
        super: 'Photon Array' },
      { name: 'Sentinel', archetype: 'Charge', difficulty: 5, popularity: 6,
        tags: ['monster', 'cheap'],
        description: 'A flying hunter-killer built to end a species. Sits in the air, throws drones, punishes impatience.',
        specials: ['Rocket Punch', 'Sentinel Force', 'Human Catapult', 'Armor Plating'],
        super: 'Plasma Storm' },
      { name: 'Mega Man', archetype: 'All-Rounder', difficulty: 4, popularity: 8,
        tags: ['classic', 'cute'],
        description: 'A blue robot boy with a dog, a bird and an answer for everything, all of which he calls in separately.',
        specials: ['Mega Buster', 'Tornado Hold', 'Leaf Shield', 'Rush Jet'],
        super: 'Hyper Mega Man' },
      { name: 'Morrigan', archetype: 'Glass Cannon', difficulty: 6, popularity: 9,
        tags: ['anime', 'creepy'],
        description: 'A succubus who fights for the fun of it, which is more terrifying than any of the reasons the others have.',
        specials: ['Astral Vision', 'Shadow Blade', 'Flight', 'Soul Fist'],
        super: 'Darkness Illusion' },
      { name: 'Strider Hiryu', archetype: 'Stance Switch', difficulty: 9, popularity: 8,
        tags: ['cool', 'technical'],
        description: 'A hired ninja with a plasma cypher and a menagerie of summoned animals. Two characters on one lifebar.',
        specials: ['Ouroboros', 'Legion', 'Gram Slash', 'Vajra'],
        super: 'Ragnarok' },
    ],
  },

  {
    key: 'guilty-gear',
    name: 'Guilty Gear',
    gameName: 'Guilty Gear',
    blurb: 'Heavy metal names, absurd movelists, and a defensive system with more rules than most games have characters.',
    tags: ['anime', 'edgy', 'flashy', 'technical', 'creepy', 'cool'],
    characters: [
      { name: 'Sol Badguy', archetype: 'Shoto', difficulty: 4, popularity: 10,
        tags: ['edgy', 'anime'],
        description: 'A bounty hunter with a lighter for a sword and a headband hiding what he actually is. Sets the pace of the game.',
        specials: ['Gunflame', 'Volcanic Viper', 'Bandit Revolver', 'Night Raid Vortex'],
        super: 'Tyrant Rave' },
      { name: 'Ky Kiske', archetype: 'All-Rounder', difficulty: 3, popularity: 8,
        tags: ['honest', 'royal'],
        description: 'A knight-captain who fights by the book, which in this game is genuinely the rarest style on the roster.',
        specials: ['Stun Edge', 'Vapor Thrust', 'Dire Eclat', 'Stun Dipper'],
        super: 'Ride the Lightning' },
      { name: 'May', archetype: 'Weapon Master', difficulty: 5, popularity: 9,
        tags: ['cute', 'big damage'],
        description: 'A pirate girl swinging a ship anchor twice her size. The whale is not a joke, it is a mechanic.',
        specials: ['Mr. Dolphin Horizontal', 'Applause for the Victim', 'Anchor Sweep', 'Mr. Dolphin Vertical', 'Beach Ball'],
        super: 'Great Yamada Attack' },
      { name: 'Potemkin', archetype: 'Grappler', difficulty: 9, popularity: 7,
        tags: ['monster', 'big damage'],
        description: 'A soldier the size of a monument who cannot dash. Gets in once a round and takes sixty percent for it.',
        specials: ['Potemkin Buster', 'Hammer Fall', 'Slide Head', 'Megafist'],
        super: 'Giganter' },
      { name: 'Millia Rage', archetype: 'Setplay', difficulty: 8, popularity: 8,
        tags: ['technical', 'cheap'],
        description: 'An assassin whose hair is both the weapon and the setup. One knockdown starts a loop nobody escapes on camera.',
        specials: ['Silent Force', 'Bad Moon', 'Emerald Rain', 'Lust Shaker'],
        super: 'Iron Savior' },
      { name: 'Faust', archetype: 'Mix-up', difficulty: 8, popularity: 8,
        tags: ['goofy', 'creepy'],
        description: 'A paper bag, a scalpel, and a sack of items nobody including the doctor can predict.',
        specials: ['Pogo Hop', 'Souvenir', 'What Could This Be?', "Hack 'n' Slash"],
        super: 'Bone-crushing Excitement' },
      { name: 'Chipp Zanuff', archetype: 'Rushdown', difficulty: 9, popularity: 8,
        tags: ['flashy', 'underdog'],
        description: 'The fastest character in the game with the smallest health bar in the game. Wins in ten seconds or loses in three.',
        specials: ['Alpha Blade', 'Rokusai', 'Shuriken', 'Gamma Blade'],
        super: 'Zansei Rouga' },
      { name: 'Zato-1', archetype: 'Puppet', difficulty: 10, popularity: 7,
        tags: ['creepy', 'technical'],
        description: 'A blind assassin and the thing living in his shadow. Two characters, one bar, a hundred hours before you may play him.',
        specials: ['Summon Eddie', 'Invite Hell', 'Drunkard Shade', 'Damned Fang'],
        super: 'Amorphous' },
      { name: 'Axl Low', archetype: 'Zoner', difficulty: 6, popularity: 8,
        tags: ['cool', 'cheap'],
        description: 'A time-lost delinquent with two chained sickles and the longest normals in the game.',
        specials: ['Sickle Flash', 'Rain Water', 'Winter Cherry', 'Spindle Spinner'],
        super: 'Byakue Rensen' },
      { name: 'Baiken', archetype: 'Counter-Puncher', difficulty: 9, popularity: 8,
        tags: ['edgy', 'technical'],
        description: 'One arm, one eye, one grudge, and a parry that turns your best pressure into her turn.',
        specials: ['Azami', 'Hiiragi', 'Tatami Gaeshi', 'Kabari'],
        super: 'Tsurane Sanzu-watashi' },
      { name: 'I-No', archetype: 'Aerial', difficulty: 7, popularity: 9,
        tags: ['flashy', 'anime'],
        description: 'A witch on a guitar who fights from the air and treats the ground as optional scenery.',
        specials: ['Hoverdash', 'Stroke the Big Tree', 'Sultry Performance', 'Antidepressant Scale'],
        super: 'Ultimate Fortissimo' },
      { name: 'Johnny', archetype: 'Footsies', difficulty: 8, popularity: 8,
        tags: ['cool', 'honest'],
        description: 'A gambler in a cowboy hat with a draw stance and a level three that has been the room\'s favourite clip for years.',
        specials: ['Mist Finer', 'Glitter is Gold', 'Divine Blade', 'Bacchus Sigh'],
        super: "That's My Name" },
    ],
  },

  {
    key: 'injustice',
    name: 'Injustice',
    gameName: 'Injustice',
    blurb: 'Costumed icons on a regime that went wrong: environmental throws through three walls, and a story mode people actually finished.',
    tags: ['edgy', 'royal', 'military', 'monster', 'flashy', 'underdog'],
    characters: [
      { name: 'Superman', archetype: 'All-Rounder', difficulty: 3, popularity: 10,
        tags: ['honest', 'royal'],
        description: 'The last son of a dead planet, and the reason the world is under new management. Good at everything, sorry about nothing.',
        specials: ['Heat Vision', 'Rising Grab', 'Ice Breath', 'Flying Punch'],
        super: 'Kryptonian Crush' },
      { name: 'Batman', archetype: 'Setplay', difficulty: 8, popularity: 10,
        tags: ['edgy', 'technical'],
        description: 'No powers, a great deal of money, and a gadget prepared for each of the eleven people on this list.',
        specials: ['Bat Swarm', 'Sticky Bomb', 'Mechanical Bats', 'Slide Kick'],
        super: 'The Dark Knight' },
      { name: 'Wonder Woman', archetype: 'Weapon Master', difficulty: 5, popularity: 9,
        tags: ['royal', 'honest'],
        description: 'A princess and a diplomat with a sword, a shield, and a rope that makes you tell the truth mid-combo.',
        specials: ['Lasso Spin', 'Amalthea Bash', 'Shield Slam', 'Up Sword', 'Tiara Toss'],
        super: 'Pride of the Amazons' },
      { name: 'The Flash', archetype: 'Rushdown', difficulty: 6, popularity: 9,
        tags: ['flashy', 'cool'],
        description: 'The fastest man alive, which in this game means he is already behind you and apologising about it.',
        specials: ['Speed Dodge', 'Lightning Charge', 'Lightning Kick', 'Sonic Pound'],
        super: 'Speed Zone' },
      { name: 'The Joker', archetype: 'Mix-up', difficulty: 7, popularity: 10,
        tags: ['creepy', 'goofy'],
        description: 'A clown with a crowbar and a plan that only makes sense if you have already lost.',
        specials: ['Rolling Laughter', 'Side Order of Pie', 'Chattering Teeth', 'Crowbar'],
        super: 'The Last Laugh' },
      { name: 'Aquaman', archetype: 'Counter-Puncher', difficulty: 6, popularity: 7,
        tags: ['royal', 'honest'],
        description: 'A monarch with a trident and a nation underwater to answer to. Waits behind a wall of water and bills you for the wait.',
        specials: ['Water Shield', 'Trident Toss', 'Trident Rush', 'Deep Dive'],
        super: 'Rage of the Seven Seas' },
      { name: 'Green Lantern', archetype: 'Puppet', difficulty: 9, popularity: 7,
        tags: ['technical', 'flashy'],
        description: 'A test pilot with a ring that builds whatever he can hold in his head, and half of it is standing elsewhere.',
        specials: ['Mini Gun', "Lantern's Might", 'Rocket Power', 'Turbine Smash'],
        super: 'Beware My Power' },
      { name: 'Bane', archetype: 'Grappler', difficulty: 5, popularity: 8,
        tags: ['big damage', 'monster'],
        description: 'A luchador on a chemical drip that turns him into a building. Very smart, which nobody expects until the mix-up.',
        specials: ['Bane Bomb', 'Double Punch', 'Venom Boost', 'Raging Charge'],
        super: 'Break the Bat' },
      { name: 'Doomsday', archetype: 'Big Body', difficulty: 4, popularity: 7,
        tags: ['monster', 'big damage'],
        description: 'An engineered extinction event with bones on the outside. Gets back up; that is the whole character.',
        specials: ['Earthshake', 'Snare', 'Air Venom', 'Regeneration'],
        super: 'Doomed' },
      { name: 'Deathstroke', archetype: 'Zoner', difficulty: 6, popularity: 9,
        tags: ['military', 'cheap'],
        description: 'A one-eyed contractor with a rifle, a sword and no side. Keeps you full screen and bills by the round.',
        specials: ['Quick Shot', 'Machine Gun', 'Sticky Grenade', 'Sword Flip'],
        super: 'Terminate' },
      { name: 'Catwoman', archetype: 'Aerial', difficulty: 6, popularity: 9,
        tags: ['cool', 'underdog'],
        description: 'A thief who fights from the rafters, on nobody\'s side but occasionally on yours.',
        specials: ['Cat Dash', 'Straight Pounce', 'Whip Trip', 'Cat Claws'],
        super: 'Cat Scratch Fever' },
      { name: 'Raven', archetype: 'Glass Cannon', difficulty: 7, popularity: 8,
        tags: ['creepy', 'edgy'],
        description: 'An empath holding a demon inside her by force of will, which she stops doing at half a health bar.',
        specials: ['Demon Stance', 'Soul Crush', 'Event Horizon', 'Pull'],
        super: 'Deadly Nightmare' },
    ],
  },

  // SNES SHOWDOWN — the house crossover, and the only preset with art of its
  // own: every fighter carries a `spriteKey` into src/assets/packs/snes-showdown.
  // Forty-eight on the select screen, which is why this one also carries the
  // roster's most crowded archetypes — a crossover is allowed four big bodies.
  {
    key: 'snes-showdown',
    name: 'SNES Showdown',
    gameName: 'SNES Showdown',
    blurb: 'The house crossover: forty-eight fighters pulled out of every cartridge on the shelf, with sprites to match.',
    tags: ['classic', 'cute', 'monster', 'flashy', 'goofy', 'royal', 'technical', 'underdog'],
    characters: [
      { name: 'Ark', archetype: 'All-Rounder', difficulty: 4, popularity: 6,
        tags: ['honest', 'classic'], spriteKey: 'snes-showdown/ark',
        description: 'Terranigma. A village boy who resurrects the surface world one continent at a time, and fights with everything he picked up doing it.',
        specials: ['Fire Ring', 'Jump Thrust', 'Deflect', 'Slide Attack'],
        super: 'Star Fragment' },
      { name: 'Bad Mr. Frosty', archetype: 'Big Body', difficulty: 3, popularity: 7,
        tags: ['goofy', 'monster'], spriteKey: 'snes-showdown/bad-mr-frosty',
        description: 'ClayFighter. A snowman in a top hat with a grudge against everybody at the circus.',
        specials: ['Belly Bounce', 'Frost Bite', 'Ice Uppercut', 'Frozen Solid'],
        super: 'Blizzard Blast' },
      { name: 'Bill Rizer', archetype: 'Glass Cannon', difficulty: 6, popularity: 7,
        tags: ['military', 'big damage'], spriteKey: 'snes-showdown/bill-rizer',
        vitality: 'glass',
        description: 'Contra. Enormous firepower, one hit point. Everything about him is the trade.',
        specials: ['Spread Gun', 'Hyper Shell', 'Combat Roll', 'Rifle Butt'],
        super: 'Laser Barrage' },
      { name: 'M. Bison', archetype: 'Mix-up', difficulty: 6, popularity: 8,
        tags: ['edgy', 'royal'], spriteKey: 'snes-showdown/bison',
        description: 'Street Fighter. Shadaloo\'s dictator, running on Psycho Power and the certainty that he outranks this entire tournament.',
        specials: ['Bison Warp', 'Head Press', 'Psycho Inferno', 'Devil Reverse'],
        super: 'Psycho Crusher' },
      { name: 'Black Mage', archetype: 'Glass Cannon', difficulty: 7, popularity: 7,
        tags: ['technical', 'creepy'], spriteKey: 'snes-showdown/black-mage',
        description: 'Final Fantasy. A hat, a pair of glowing eyes, and the entire offensive spell list. Nothing underneath.',
        specials: ['Focus', 'Meteor', 'Warp', 'Drain'],
        super: 'Ultima' },
      { name: 'Bomberman', archetype: 'Setplay', difficulty: 6, popularity: 9,
        tags: ['cute', 'technical'], spriteKey: 'snes-showdown/bomberman',
        description: 'Bomberman. Turns the stage into a grid of things about to go off, then walks you into one.',
        specials: ['Bomb', 'Remote Bomb', 'Fire Up', 'Bomb Kick'],
        super: 'Full Fire' },
      { name: 'Bowser', archetype: 'Grappler', difficulty: 4, popularity: 9,
        tags: ['monster', 'royal'], spriteKey: 'snes-showdown/bowser',
        description: 'Super Mario. A spiked tyrant king who takes hits like weather and gives them back like a building falling.',
        specials: ['Koopa Klaw', 'Bowser Bomb', 'Fire Breath', 'Whirling Fortress'],
        super: 'Flying Slam' },
      { name: 'Chocobo', archetype: 'Rushdown', difficulty: 4, popularity: 9,
        tags: ['cute', 'goofy'], spriteKey: 'snes-showdown/chocobo',
        description: 'Final Fantasy. A giant yellow bird that has never once been asked whether it wanted to be here. Wark.',
        specials: ['Chocobo Dash', 'Choco Peck', 'Wark Flurry', 'Choco Kick'],
        super: 'Choco Meteor' },
      { name: 'Cormano Wild', archetype: 'Counter-Puncher', difficulty: 6, popularity: 6,
        tags: ['cool', 'honest'], spriteKey: 'snes-showdown/cormano-wild',
        description: 'Sunset Riders. A gunslinger in a pink poncho and a sombrero who wins every draw he is patient enough to wait for.',
        specials: ['Quick Draw', 'Ricochet', 'Shotgun Blast', 'Sidestep Roll'],
        super: 'Sunset Standoff' },
      { name: 'Crono', archetype: 'Shoto', difficulty: 3, popularity: 9,
        tags: ['honest', 'classic'], spriteKey: 'snes-showdown/crono',
        description: 'Chrono Trigger. Red hair, a katana, and not one line of dialogue in the entire tournament.',
        specials: ['Lightning', 'Cyclone', 'Slash', 'Dash'],
        super: 'Luminaire' },
      { name: 'Diddy Kong', archetype: 'Rushdown', difficulty: 5, popularity: 8,
        tags: ['cute', 'flashy'], spriteKey: 'snes-showdown/diddy-and-dixie_diddy',
        description: 'Donkey Kong Country. Half a tag team. Fast, small, and one tag away from something with better air control.',
        specials: ['Cartwheel', 'Monkey Flip', 'Peanut Popgun', 'Rocketbarrel Blast'],
        super: 'Barrel Blast',
        forms: [
          { name: 'Dixie Kong', archetype: 'Aerial', difficulty: 5, popularity: 8,
            tags: ['cute', 'flashy'], spriteKey: 'snes-showdown/diddy-and-dixie_dixie',
            description: 'The other half. That ponytail is a helicopter, and the ground stops being a constraint.',
            specials: ['Helicopter Spin', 'Hair Slam', 'Ponytail Snatch', 'Hair Whip'],
            super: 'Rocketbarrel Barrage',
            via: 'Tag In: Dixie', revert: 'Tag In: Diddy' },
        ] },
      { name: 'Donkey Kong', archetype: 'Big Body', difficulty: 3, popularity: 9,
        tags: ['monster', 'big damage'], spriteKey: 'snes-showdown/donkey-kong',
        description: 'Donkey Kong Country. Barrel chest, necktie, and a wind-up punch you can see coming from the parking lot.',
        specials: ['Giant Punch', 'Cargo Throw', 'Spinning Kong', 'Hand Slap'],
        super: 'Konga Beat' },
      { name: 'Dr. Wily', archetype: 'Puppet', difficulty: 10, popularity: 6,
        tags: ['technical', 'creepy'], spriteKey: 'snes-showdown/dr.wily',
        description: 'Mega Man. Never gets out of the saucer. Never has to — he brought eight robots and a schedule.',
        specials: ['Call a Robot Master', 'Capsule Orb', 'Hover Thrust', 'Saucer Ram'],
        super: 'Wily Machine' },
      { name: 'Dracula', archetype: 'Setplay', difficulty: 8, popularity: 9,
        tags: ['creepy', 'royal'], spriteKey: 'snes-showdown/dracula',
        description: 'Castlevania. Rises every hundred years, teleports twice, and asks what is a man.',
        specials: ['Hellfire', 'Dark Inferno', 'Bat Form', 'Demonic Sweep'],
        super: 'Chaos Ripper' },
      { name: 'Earthworm Jim', archetype: 'Mix-up', difficulty: 7, popularity: 8,
        tags: ['goofy', 'flashy'], spriteKey: 'snes-showdown/earthworm-jim',
        description: 'Earthworm Jim. A worm in a robot suit who uses himself as the whip. Groovy.',
        specials: ['Snott Swing', 'Worm Whip', 'Plasma Mine', 'Head Slam'],
        super: 'Cow Launch' },
      { name: 'Fox McCloud', archetype: 'Rushdown', difficulty: 6, popularity: 8,
        tags: ['cool', 'military'], spriteKey: 'snes-showdown/fox',
        description: 'Star Fox. A pilot fighting on foot because the Arwing does not fit through the door.',
        specials: ['Fox Illusion', 'Fire Fox', 'Blaster', 'Reflector'],
        super: 'Landmaster' },
      { name: 'Frog', archetype: 'Footsies', difficulty: 6, popularity: 8,
        tags: ['honest', 'underdog'], spriteKey: 'snes-showdown/frog',
        description: 'Chrono Trigger. A knight cursed into an amphibian, still the most honourable fighter in the bracket.',
        specials: ['Slurp', 'Leap Slash', 'Slurp Cut', 'Water Slice'],
        super: 'Masamune Strike' },
      { name: 'Ganon', archetype: 'Big Body', difficulty: 5, popularity: 9,
        tags: ['monster', 'royal'], spriteKey: 'snes-showdown/ganon',
        description: 'The Legend of Zelda. The King of Evil, a trident, and a hitbox that takes up a third of the screen.',
        specials: ['Trident Slam', 'Dark Grip', 'Rising Trident', 'Dark Guard'],
        super: "Dead Man's Volley" },
      { name: 'Geno', archetype: 'Zoner', difficulty: 6, popularity: 8,
        tags: ['cool', 'technical'], spriteKey: 'snes-showdown/geno',
        description: 'Super Mario RPG. A star spirit wearing a toy. Every limb he has is also a gun.',
        specials: ['Geno Beam', 'Geno Blast', 'Geno Flash', 'Hand Gun'],
        super: 'Geno Whirl' },
      { name: 'Goemon', archetype: 'Footsies', difficulty: 6, popularity: 7,
        tags: ['classic', 'goofy'], spriteKey: 'snes-showdown/goemon',
        description: 'Mystical Ninja. A folk-hero thief with a smoking pipe for a weapon and a giant robot on speed dial.',
        specials: ['Coin Parry', 'Goemon Dash', 'Pipe Swing', 'Low Sweep'],
        super: 'Impact Summon' },
      { name: 'Haggar', archetype: 'Grappler', difficulty: 5, popularity: 8,
        tags: ['big damage', 'honest'], spriteKey: 'snes-showdown/haggar',
        description: 'Final Fight. The mayor. Solves municipal problems by piledriving them into the pavement.',
        specials: ['Spinning Piledriver', 'Double Lariat', 'Body Splash', 'Shoulder Charge'],
        super: 'Final Haggar Buster' },
      { name: 'Randy', archetype: 'All-Rounder', difficulty: 5, popularity: 8,
        tags: ['honest', 'classic'], spriteKey: 'snes-showdown/heroes-of-mana_randy',
        description: 'Secret of Mana. Pulled the sword out, got exiled for it, and brought two friends he can swap to at any time.',
        specials: ['Sword Wave', 'Rising Slash', 'Guard', 'Dash'],
        super: 'Mana Blade',
        forms: [
          { name: 'Popoi', archetype: 'Zoner', difficulty: 7, popularity: 7,
            tags: ['technical', 'cute'], spriteKey: 'snes-showdown/heroes-of-mana_popoi',
            description: 'The sprite. Every elemental in the game lives in that little book, and none of them are defensive.',
            specials: ['Fireball', 'Freeze', 'Earth Slide', 'Air Blast'],
            super: 'Exploder',
            via: 'Swap: Popoi', revert: 'Randy Takes the Lead' },
          { name: 'Primm', archetype: 'Setplay', difficulty: 7, popularity: 7,
            tags: ['technical', 'royal'], spriteKey: 'snes-showdown/heroes-of-mana_primm',
            description: 'The girl who came for a boy and stayed for the war. Light, shadow, and everything that makes a knockdown last.',
            specials: ['Lucent Beam', 'Dark Force', 'Lunar Boost', 'Light Sweep'],
            super: 'Saint Beam',
            via: 'Swap: Primm', revert: 'Randy Takes the Lead' },
        ] },
      { name: 'Zeke', archetype: 'Zoner', difficulty: 6, popularity: 7,
        tags: ['goofy', 'underdog'], spriteKey: 'snes-showdown/zeke',
        skins: [{ name: 'Julie', spriteKey: 'snes-showdown/julie' }],
        description: 'Zombies Ate My Neighbors. A kid in 3D glasses with a super soaker, fighting a B-movie with the contents of a garage.',
        specials: ['Super Soaker', 'Soda Can Bomb', 'Bazooka Mine', 'Weed Whacker'],
        super: 'Bazooka Barrage' },
      { name: 'Ryu', archetype: 'Shoto', difficulty: 3, popularity: 10,
        tags: ['honest', 'classic'], spriteKey: 'snes-showdown/ryu',
        skins: [{ name: 'Ken', spriteKey: 'snes-showdown/ken' }],
        description: 'Street Fighter. The measuring stick. Fireball, uppercut, honest buttons — the yardstick this whole cartridge shelf is measured against.',
        specials: ['Hadoken', 'Shoryuken', 'Tatsumaki Senpukyaku', 'Collarbone Breaker'],
        super: 'Shinku Hadoken' },
      { name: 'King Dedede', archetype: 'Big Body', difficulty: 4, popularity: 8,
        tags: ['goofy', 'royal'], spriteKey: 'snes-showdown/king-dedede',
        description: 'Kirby. A self-appointed penguin king with a hammer bigger than his claim to the throne.',
        specials: ['Jet Hammer', 'Dedede Grab', 'Super Dedede Jump', 'Gordo Guard'],
        super: 'Waddle Dee Army' },
      { name: 'King K. Rool', archetype: 'Charge', difficulty: 5, popularity: 8,
        tags: ['monster', 'royal'], spriteKey: 'snes-showdown/king-k-rool',
        description: 'Donkey Kong Country. A crocodile pirate king with a blunderbuss, a cape, and a different costume every rematch.',
        specials: ['Blunderbuss', 'Crownerang', 'Belly Charge', 'Gut Check'],
        super: 'Blast-o-Matic' },
      { name: 'Kirby', archetype: 'Stance Switch', difficulty: 8, popularity: 10,
        tags: ['cute', 'technical'], spriteKey: 'snes-showdown/kirby',
        description: 'Kirby. A pink sphere that swallows what you do and does it back. Nothing about him is threatening to look at.',
        specials: ['Copy', 'Stone', 'Hammer Flip', 'Inhale'],
        super: 'Cook Kirby' },
      { name: 'Knight Arthur', archetype: 'Glass Cannon', difficulty: 8, popularity: 7,
        tags: ['classic', 'underdog'], spriteKey: 'snes-showdown/knight-arthur',
        vitality: 'glass',
        description: 'Ghosts \'n Goblins. One hit takes the armour, two takes the knight. Throws lances the entire time regardless.',
        specials: ['Golden Armor', 'Axe Throw', 'Armor Roll', 'Lance Jab'],
        super: 'Psycho Cannon' },
      { name: 'Link', archetype: 'Weapon Master', difficulty: 4, popularity: 10,
        tags: ['honest', 'cool'], spriteKey: 'snes-showdown/link',
        description: 'The Legend of Zelda. Sword, shield and a bag of tools. Fights at exactly the range where his steel is and your fists are not.',
        specials: ['Spin Attack', 'Sword Slash', 'Shield Sweep', 'Up Thrust', 'Boomerang'],
        super: 'Silver Arrow' },
      { name: 'Mario', archetype: 'All-Rounder', difficulty: 2, popularity: 10,
        tags: ['classic', 'cute'], spriteKey: 'snes-showdown/mario',
        skins: [{ name: 'Luigi', spriteKey: 'snes-showdown/luigi' }],
        description: 'Super Mario. The mascot. A tool for every situation, a weakness nowhere, and the face on the box.',
        specials: ['Fireball', 'Super Jump Punch', 'Cape', 'Mario Tornado'],
        super: 'Mario Finale' },
      { name: 'Mai Shiranui', archetype: 'Aerial', difficulty: 6, popularity: 9,
        tags: ['flashy', 'cool'], spriteKey: 'snes-showdown/mai',
        description: 'Fatal Fury. A kunoichi who fights with folding fans and spends most of the round somewhere above your head.',
        specials: ['Musasabi no Mai', 'Hissatsu Shinobibachi', 'Hakuro no Mai', 'Ryu En Bu'],
        super: 'Chou Hissatsu Shinobibachi' },
      { name: 'Mega Man', archetype: 'Charge', difficulty: 4, popularity: 10,
        tags: ['classic', 'honest'], spriteKey: 'snes-showdown/megaman',
        description: 'Mega Man. Holds the buster down all round and makes you respect the release.',
        specials: ['Mega Buster', 'Rising Buster', 'Charge Shot', 'Leaf Shield'],
        super: 'Hyper Mega Man' },
      { name: 'Peach', archetype: 'Counter-Puncher', difficulty: 6, popularity: 9,
        tags: ['royal', 'cute'], spriteKey: 'snes-showdown/peach',
        description: 'Super Mario. Floats, waits, and answers your best button with a vegetable and a Toad.',
        specials: ['Toad', 'Parasol Guard', 'Peach Bomber', 'Float'],
        super: 'Peach Blossom' },
      { name: 'Pete', archetype: 'Setplay', difficulty: 7, popularity: 5,
        tags: ['goofy', 'underdog'], spriteKey: 'snes-showdown/pete',
        description: 'Harvest Moon. A farmer with a hoe, a sickle and a season\'s patience. Plants something at round start and collects at the end of it.',
        specials: ['Plant Seeds', 'Beehive', 'Stamina Meal', 'Sickle Sweep'],
        super: 'Harvest Festival' },
      { name: 'Quote', archetype: 'Zoner', difficulty: 6, popularity: 7,
        tags: ['technical', 'underdog'], spriteKey: 'snes-showdown/quote',
        skins: [{ name: 'Curly Brace', spriteKey: 'snes-showdown/curly' }],
        description: 'Cave Story. A soldier robot who forgot the mission. Levels his gun up by hitting things and down by getting hit.',
        specials: ['Spur', 'Missile Launcher', 'Bubbline', 'Machine Gun Lift'],
        super: 'Blade' },
      { name: 'Samus', archetype: 'Zoner', difficulty: 5, popularity: 9,
        tags: ['military', 'technical'], spriteKey: 'snes-showdown/samus',
        description: 'Metroid. A bounty hunter in a suit of borrowed Chozo engineering. Charges a beam and makes the screen a hallway.',
        specials: ['Charge Shot', 'Missile', 'Bomb', 'Screw Attack'],
        super: 'Zero Laser' },
      { name: 'Shantae', archetype: 'Stance Switch', difficulty: 8, popularity: 8,
        tags: ['flashy', 'technical'], spriteKey: 'snes-showdown/shantae',
        description: 'Shantae. A half-genie who dances into whatever animal the situation calls for, and whips you with her hair in between.',
        specials: ['Monkey Dance', 'Elephant Dance', 'Hair Whip', 'Harpy Guard'],
        super: 'Dance of Storms' },
      { name: 'Simon Belmont', archetype: 'Weapon Master', difficulty: 5, popularity: 9,
        tags: ['classic', 'honest'], spriteKey: 'snes-showdown/simon',
        description: 'Castlevania. A whip, a stopwatch, and a family obligation that comes due every hundred years.',
        specials: ['Whip Crack', 'Holy Water', 'Low Whip', 'Cross Boomerang', 'Dagger'],
        super: 'Grand Cross' },
      { name: 'Slime', archetype: 'Puppet', difficulty: 7, popularity: 9,
        tags: ['cute', 'monster'], spriteKey: 'snes-showdown/slime',
        description: 'Dragon Quest. The first enemy anybody ever killed, here to file a complaint. Splits, and the copies file too.',
        specials: ['Split', 'Slime Puddle', 'Bounce', 'Body Slam'],
        super: 'King Slime' },
      { name: 'Sonic', archetype: 'Rushdown', difficulty: 5, popularity: 10,
        tags: ['cool', 'flashy'], spriteKey: 'snes-showdown/sonic',
        description: 'Sonic the Hedgehog. On the wrong console and unbothered about it. Never stops moving; never stops talking either.',
        specials: ['Spin Dash', 'Homing Attack', 'Spin Attack', 'Stomp'],
        super: 'Super Sonic' },
      { name: 'Tails', archetype: 'Aerial', difficulty: 5, popularity: 8,
        tags: ['cute', 'underdog'], spriteKey: 'snes-showdown/tails',
        description: 'Sonic the Hedgehog. Two tails, a wrench, and better flight than anybody else in the bracket.',
        specials: ['Tail Flight', 'Tail Drop', 'Fly and Carry', 'Tail Swipe'],
        super: 'Tornado' },
      { name: 'Terra', archetype: 'Zoner', difficulty: 7, popularity: 9,
        tags: ['anime', 'royal'], spriteKey: 'snes-showdown/terra',
        description: 'Final Fantasy VI. Half esper, raised as a weapon, still working out which half is hers.',
        specials: ['Firaga', 'Blizzaga', 'Thundaga', 'Holy'],
        super: 'Ultima',
        forms: [
          { name: 'Esper Terra', archetype: 'Glass Cannon', difficulty: 7, popularity: 9,
            tags: ['anime', 'big damage'], spriteKey: 'snes-showdown/terra_esper-terra',
            description: 'The other half, off the leash. Magic goes up, everything keeping her standing goes down.',
            specials: ['Magitek Aura', 'Riot Blade', 'Warp', 'Drain'],
            super: 'Meteor',
            via: 'Morph', revert: 'Revert' },
        ] },
      { name: 'The Master', archetype: 'Charge', difficulty: 6, popularity: 6,
        tags: ['royal', 'honest'], spriteKey: 'snes-showdown/the-master',
        description: 'ActRaiser. A god who came down to do it personally, and brought the weather with him.',
        specials: ['Magical Fire', 'Rising Sword', 'Stardust', 'Aura'],
        super: "Angel's Arrow" },
      { name: 'TMNT', archetype: 'Weapon Master', difficulty: 5, popularity: 9,
        tags: ['cool', 'goofy'], spriteKey: 'snes-showdown/TMNT_leonardo',
        skins: [
          { name: 'Leonardo', spriteKey: 'snes-showdown/TMNT_leonardo' },
          { name: 'Raphael', spriteKey: 'snes-showdown/TMNT_rafael' },
          { name: 'Donatello', spriteKey: 'snes-showdown/TMNT_donatello' },
          { name: 'Michelangelo', spriteKey: 'snes-showdown/TMNT_michelangelo' },
        ],
        description: 'Teenage Mutant Ninja Turtles. Four brothers, four weapons, one slot on the select screen. Whoever shows up, the reach is the same.',
        specials: ['Weapon Spin', 'Overhead Cleave', 'Low Sweep', 'Rising Strike', 'Shell Check'],
        super: 'Turtle Power' },
      { name: 'Yoshi', archetype: 'Grappler', difficulty: 4, popularity: 9,
        tags: ['cute', 'goofy'], spriteKey: 'snes-showdown/yoshi-and-baby-mario',
        description: 'Yoshi\'s Island. Eats you, and what comes out the other side is an egg. Carries a baby through the whole tournament.',
        specials: ['Egg Lay', 'Ground Pound', 'Egg Throw', 'Flutter Jump'],
        super: 'Super Dragon' },
      { name: 'Zero', archetype: 'Rushdown', difficulty: 7, popularity: 9,
        tags: ['cool', 'anime'], spriteKey: 'snes-showdown/zero',
        description: 'Mega Man X. Blond ponytail, beam sabre, and a habit of dying heroically that has never once stuck.',
        specials: ['Air Dash', 'Z-Saber Combo', 'Raijingeki', 'Hyouretsuzan'],
        super: 'Rekkoha' },
      { name: 'Zelda', archetype: 'Counter-Puncher', difficulty: 7, popularity: 9,
        tags: ['royal', 'technical'], spriteKey: 'snes-showdown/zelda',
        description: 'The Legend of Zelda. Does nothing at all until you commit, and the thing she does about it reflects.',
        specials: ["Nayru's Love", 'Light Shield', 'Phantom Slash', "Farore's Wind"],
        super: 'Light Arrow' },
      { name: 'Will', archetype: 'All-Rounder', difficulty: 8, popularity: 7,
        tags: ['underdog', 'technical'], spriteKey: 'snes-showdown/will',
        description: 'Illusion of Gaia. A schoolboy with a flute and two other people living in him.',
        specials: ['Flute Wave', 'Spin Dash', 'Aura Barrier', 'Psycho Dash'],
        super: 'Psycho Slider',
        forms: [
          { name: 'Freedan', archetype: 'Weapon Master', difficulty: 8, popularity: 7,
            tags: ['edgy', 'cool'], spriteKey: 'snes-showdown/will_freedan',
            description: 'The dark knight. Everything Will cannot reach, Freedan reaches with a sword twice his height.',
            specials: ['Spin Slash', 'Dark Friar', 'Low Cleave', 'Aura Guard', 'Hilt Check'],
            super: 'Dark Friar Burst',
            via: 'Become Freedan', revert: 'Return to Will' },
          { name: 'Shadow', archetype: 'Glass Cannon', difficulty: 8, popularity: 7,
            tags: ['anime', 'big damage'], spriteKey: 'snes-showdown/will_shadow',
            description: 'The light form. Untouchable for as long as it lasts, and it does not last.',
            specials: ['Light Aura', 'Firebird', 'Phase Step', 'Light Slash'],
            super: 'Firebird Charge',
            via: 'Become Shadow', revert: 'Return to Will' },
        ] },
    ],
  },
]
